services:
  server:
    build:
      context: .
      target: server
    container_name: nestjs-app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - app-network
    command: ["pnpm", "run", "--filter=server", "dev"]

  web:
    build:
      context: .
      target: web
    container_name: nextjs-app
    command: ["pnpm", "run", "--filter=web", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge
